### ISSUE TITLE
Proposal Peer Review

### ISSUE THREAD

**Issue by nithingm** [INFO-526-FA24/project-2-infocrew#1]
**Peer Review for Team Infocrew’s Proposal: Visualization Cheat Sheet**

Reviewer Team: Insight Spark
Reviewer Members: Disha (Disha-98), Nithin (nithingm), Rony(ronymacwan), Sharan (Sharanpazhanivel)

**Describe the goal of the project.**

The goal of the project is to create a "Visualization Cheat Sheet" that provides an overview of various data visualizations available in R. The aim is to produce a guide for research students and other audience members with limited visualization experience, helping them choose apt visualization types based on their data and research questions. By generating examples of popular visualizations and providing a comparison (e.g., Histogram vs. Bar Graph), the goal is to aid users in understanding how different visualizations can be used effectively.

**Describe the data used or collected.**

The plan is to use built-in datasets in R, such as the MPG, Penguin, and Iris flower datasets, due to their diversity in data types and structures. These datasets are commonly used in data visualization demonstrations, offering a range of numerical and categorical data that can showcase various chart types. 

**Describe how the research question will be answered, e.g., what approaches/methods will be used.**

To address their research questions, Infocrew plans to generate examples of visualizations using R’s built-in datasets. They intend to explain the appropriate contexts for each visualization type, including color selection strategies and comparisons between similar visualizations. For example, they will likely produce visual examples of histograms, bar charts, scatter plots, and box plots. The team also mentioned they would compare visualizations like histograms and bar graphs to clarify differences and use cases. However, the proposal lacks specifics on how these explanations and visualizations will be structured within the final "cheat sheet" poster, which makes it slightly difficult to fully evaluate their methodology.

**Is there anything that is unclear from the proposal?**

1. The purpose and structure of the "cheat sheet" poster remain somewhat vague. It’s not clear if the poster is intended as a simple reference with visual examples or if it will include in-depth guidance on selecting the right visualization for specific data types.
2. The dataset choices are not fully justified, and it’s unclear if the plan is to introduce additional datasets or if they are finalizing their choices with these three.
3. The proposal mentions exploring color usage in visualizations but does not specify if they will offer guidelines for color schemes or if they will show examples with different color palettes.

**Provide constructive feedback on how the team might be able to improve their project.**

1. Clarifying the purpose and content of the cheat sheet. 
Clearly outline whether this cheat sheet is meant to be a quick reference or an educational guide. Including a structural 
outline (e.g., sections for "Types of Charts," "Best Use Cases," etc) would make this easier for users to navigate.
2. Justifying dataset choices.
Explain how each dataset will demonstrate a specific visualization type or technique. For example, “The Iris dataset will 
demonstrate scatter plots and box plots to illustrate multivariate data.” This will make it clearer why these datasets were 
selected. Also, data types like Time-series, Hierarchical, Ordinal, Spatial are not shown here. Maybe other datasets can be 
used for this or it can be mentioned that the project will be dealing mainly with visualizations for numerical and categorical data types.  
3. Detailing the comparison of visualizations.
Expanding on the approach to comparing similar visualizations like histograms vs. bar charts would add value. Specifying what criteria will be used to compare these charts will help users understand each visualization’s strengths and weaknesses.

**What aspect of this project are you most interested in and would like to see highlighted in the presentation?**

We are most interested in seeing the visual comparison between similar chart types (e.g., histogram vs. bar chart) and learning how they’ll explain the choice of one over the other in specific data contexts. We are eager to check out the poster and how it can help show the best visualization techniques.

**Provide constructive feedback on any issues with file and/or code organization.**

The task table in the proposal is currently a bit vague, especially in terms of where code or files for each task are located or will be saved. Including the expected filenames in each task's description will help clarify which files are needed or expected for each deliverable (e.g., create_proposal.Rmd, data_exploration.R, final_poster.Rmd).
Organize files into folders based on functionality to keep things orderly.

**(Optional) Any further comments or feedback?**

**Comment by tallapaneniv** [comment]
- **Describe the goal of the project.**

Reviewer's Comment:
The goal of the project is to create a "Visualization Cheat Sheet" that provides an overview of various data visualizations available in R. The aim is to produce a guide for research students and other audience members with limited visualization experience, helping them choose apt visualization types based on their data and research questions. By generating examples of popular visualizations and providing a comparison (e.g., Histogram vs. Bar Graph), the goal is to aid users in understanding how different visualizations can be used effectively.

Reviewee's Comment:
Accurate.

- **Describe the data used or collected.**

Reviewer's Comment:
The plan is to use built-in datasets in R, such as the MPG, Penguin, and Iris flower datasets, due to their diversity in data types and structures. These datasets are commonly used in data visualization demonstrations, offering a range of numerical and categorical data that can showcase various chart types.

Reviewee's Comment:
Yes, These datasets were used due to their diverse data types. 

- **Describe how the research question will be answered, e.g., what approaches/methods will be used.**

Reviewer's Comment:
To address their research questions, Infocrew plans to generate examples of visualizations using R’s built-in datasets. They intend to explain the appropriate contexts for each visualization type, including color selection strategies and comparisons between similar visualizations. For example, they will likely produce visual examples of histograms, bar charts, scatter plots, and box plots. The team also mentioned they would compare visualizations like histograms and bar graphs to clarify differences and use cases. However, the proposal lacks specifics on how these explanations and visualizations will be structured within the final "cheat sheet" poster, which makes it slightly difficult to fully evaluate their methodology.

Reviewee's Comment:
The poster structure is yet to be decided. so I apologies for the difficulty. 

- **Is there anything that is unclear from the proposal?**

Reviewer's Comment:
The purpose and structure of the "cheat sheet" poster remain somewhat vague. It’s not clear if the poster is intended as a simple reference with visual examples or if it will include in-depth guidance on selecting the right visualization for specific data types.
The dataset choices are not fully justified, and it’s unclear if the plan is to introduce additional datasets or if they are finalizing their choices with these three.
The proposal mentions exploring color usage in visualizations but does not specify if they will offer guidelines for color schemes or if they will show examples with different color palettes.

Reviewee's Comment:
The Idea for now is to provide some popular general purpose visualizations that can work for a wide variety of datasets.

The reason for choosing those three datasets was de to their diverse nature.

No, These datasets are not finalized yet. We plan on getting external datasets in future if these datasets fall short for the visualizations chosen for the project.

As for the color aspects of the projects, we plan on showing few examples of different color palettes and the reason why those are good.

- **Provide constructive feedback on how the team might be able to improve their project.**

Reviewer's Comment:
Clarifying the purpose and content of the cheat sheet.
Clearly outline whether this cheat sheet is meant to be a quick reference or an educational guide. Including a structural
outline (e.g., sections for "Types of Charts," "Best Use Cases," etc) would make this easier for users to navigate.
Justifying dataset choices.
Explain how each dataset will demonstrate a specific visualization type or technique. For example, “The Iris dataset will
demonstrate scatter plots and box plots to illustrate multivariate data.” This will make it clearer why these datasets were
selected. Also, data types like Time-series, Hierarchical, Ordinal, Spatial are not shown here. Maybe other datasets can be
used for this or it can be mentioned that the project will be dealing mainly with visualizations for numerical and categorical data types.
Detailing the comparison of visualizations.
Expanding on the approach to comparing similar visualizations like histograms vs. bar charts would add value. Specifying what criteria will be used to compare these charts will help users understand each visualization’s strengths and weaknesses.

Reviewee's Comment:
This Cheat sheet leans more towards quick reference than educational guide.

As for the structural outline part. We like it and would like to incorporate it in some form.

We haven't yet narrowed the visualizations we would like to include in our project hence no mention of the data the dataset and visualization drawn with it. The external dataset/s if we happen to choose in future will include the datatypes that the chosen datasets lack.

- **What aspect of this project are you most interested in and would like to see highlighted in the presentation?**

Reviewer's Comment:
We are most interested in seeing the visual comparison between similar chart types (e.g., histogram vs. bar chart) and learning how they’ll explain the choice of one over the other in specific data contexts. We are eager to check out the poster and how it can help show the best visualization techniques.

Reviewee's Comment:
We will do our best.

- **Provide constructive feedback on any issues with file and/or code organization.**

Reviewer's Comment:
The task table in the proposal is currently a bit vague, especially in terms of where code or files for each task are located or will be saved. Including the expected filenames in each task's description will help clarify which files are needed or expected for each deliverable (e.g., create_proposal.Rmd, data_exploration.R, final_poster.Rmd).
Organize files into folders based on functionality to keep things orderly.

Reviewee's Comment:
Task table and repo structure have been  updated.

- **(Optional) Any further comments or feedback?**
