### ISSUE TITLE
Project peer review by team Data Nexus

### ISSUE THREAD

**Issue by jolly09-ai** [INFO-526-FA24/project-2-infocrew#2]
The following is the peer review of the project proposal by Data Nexus. The team members that participated in this review are 

- Aditya jolly - @jolly09-ai
- Anubhav Mathur - @anubhavbruce
- Nitya Tejaswi Attili - @nityaattili
- Siddheshwar Singh Negi -@SSNEGI1996

- Describe the goal of the project.

The goal of this project is to create a poster that serves as a comprehensive cheat sheet for visualizations in R. It aims to educate research students without a data visualization background on selecting the best visualization techniques for their data. The project intends to cover various visualization types, demonstrate their applications, and highlight the differences between similar charts like histograms and bar graphs.

- Describe the data used or collected.

The project plans to use pre-built datasets available in R, such as:
MPG Dataset: Vehicle mileage data.
Penguin Dataset: Data on penguin species, sizes, and habitats.
Iris Dataset: Classic dataset on iris flowers, with features like sepal length and species type.

These datasets provide diverse data structures and characteristics, making them ideal for demonstrating different visualization types.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

The project addresses two key questions:
1. What role does color play in data visualization, and how can it be used effectively?

Approach:
Explore best practices for color usage in visualizations.
Demonstrate recommended color palettes for different data types using visual examples.
Compare palettes for categorical, ordinal, and continuous data

- Is there anything that is unclear from the proposal?

The proposal is clear and well-structured, but a few areas could use more detail:

Timeline Details: While the tasks are listed, the descriptions for certain steps (e.g., "Data cleaning and exploration") are vague. Specific steps or methods could be added for clarity.

Data Visualization Examples: It would be helpful to include specific visualization types planned for each dataset or research question.

- Provide constructive feedback on how the team might be able to improve their project.

1. Expanded Dataset Scope:

While using in-built datasets simplifies the process, including one external dataset relevant to research students' interests could increase the project's impact.

2. Clear Comparison Framework:

For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

3. Interactive Elements:

Consider creating interactive visualizations (using tools like plotly) to add engagement. This would allow the audience to explore data and understand visual differences better.

4. File and Code Organization:

Ensure that the code used for creating visualizations is modular and well-documented. Include a README file to describe dependencies, execution instructions, and file structure.

5. Color Accessibility:

When discussing color usage, include accessibility considerations, such as colorblind-friendly palettes or the use of patterns for differentiation.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

The most interesting aspect of the project is the comparison between similar visualization types (e.g., histogram vs. bar graph). Highlighting their specific use cases will provide valuable insights for the audience. Additionally, the exploration of how color influences visual effectiveness is compelling and has practical applications for researchers.

- Provide constructive feedback on any issues with file and/or code organization.

Use a structured folder system:

data/: For datasets.

scripts/: For R scripts.

output/: For generated visualizations.

poster/: For the final poster file.

- (Optional) Any further comments or feedback?

This project has significant potential to be both educational and visually engaging. Including a small section on the ethical considerations of data visualization (e.g., avoiding misleading visuals) could further enhance its value. Excellent work so far—looking forward to seeing the final poster and presentation!

**Comment by tallapaneniv** [comment]
- Describe the goal of the project.
**Reviewer's Comment:**
The goal of this project is to create a poster that serves as a comprehensive cheat sheet for visualizations in R. It aims to educate research students without a data visualization background on selecting the best visualization techniques for their data. The project intends to cover various visualization types, demonstrate their applications, and highlight the differences between similar charts like histograms and bar graphs.

**Reviewee's Comment:**
Accurate.

- Describe the data used or collected.
**Reviewer's Comment:**
The project plans to use pre-built datasets available in R, such as:

1. MPG Dataset: Vehicle mileage data.
2. Penguin Dataset: Data on penguin species, sizes, and habitats.
3. Iris Dataset: Classic dataset on iris flowers, with features like sepal length and species type.

These datasets provide diverse data structures and characteristics, making them ideal for demonstrating different visualization types.

**Reviewee's Comment:**
Yes, the diverse nature of these in-build datasets are the reason they for chosen for this project.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Reviewer's Comment:
The project addresses two key questions:
What role does color play in data visualization, and how can it be used effectively?
Approach:
Explore best practices for color usage in visualizations.
Demonstrate recommended color palettes for different data types using visual examples.
Compare palettes for categorical, ordinal, and continuous data

**Reviewee's Comment:**
Accurate.

- Is there anything that is unclear from the proposal?
**Reviewer's Comment:**
The proposal is clear and well-structured, but a few areas could use more detail:

Timeline Details: While the tasks are listed, the descriptions for certain steps (e.g., "Data cleaning and exploration") are vague. Specific steps or methods could be added for clarity.

Data Visualization Examples: It would be helpful to include specific visualization types planned for each dataset or research question.

**Reviewee's Comment:**
We will work on the attack tasks plan to be more detailed.

The Reason for not including Data Visualization example is because we haven't yet narrowed down on what visualizations to use but we will revise the proposal in future once we have those narrowed down.


- Provide constructive feedback on how the team might be able to improve their project.
**Reviewer's Comment:**
Expanded Dataset Scope:
While using in-built datasets simplifies the process, including one external dataset relevant to research students' interests could increase the project's impact.

Clear Comparison Framework:
For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

Interactive Elements:
Consider creating interactive visualizations (using tools like plotly) to add engagement. This would allow the audience to explore data and understand visual differences better.

File and Code Organization:
Ensure that the code used for creating visualizations is modular and well-documented. Include a README file to describe dependencies, execution instructions, and file structure.

Color Accessibility:
When discussing color usage, include accessibility considerations, such as colorblind-friendly palettes or the use of patterns for differentiation.

**Reviewee's Comment:**
The Reason we opted out of using interactive visualizations is because the end project of this project is a poster which is a static  so we thought we could create the interactivity via texts instead.

We will see to it that there is a part of poster highlighting the accessibility considerations.

The Repo structure has been updated.


- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
**Reviewer's Comment:**
For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

The most interesting aspect of the project is the comparison between similar visualization types (e.g., histogram vs. bar graph). Highlighting their specific use cases will provide valuable insights for the audience. Additionally, the exploration of how color influences visual effectiveness is compelling and has practical applications for researchers.

**Reviewee's Comment:**
Yes, We feel the same way.


- Provide constructive feedback on any issues with file and/or code organization.
**Reviewer's Comment:**
Use a structured folder system:

data/: For datasets.

scripts/: For R scripts.

output/: For generated visualizations.

poster/: For the final poster file.

**Reviewee's Comment:**
The Repo Structure has been updated accordingly

- (Optional) Any further comments or feedback?
**Reviewer's Comments:**
This project has significant potential to be both educational and visually engaging. Including a small section on the ethical considerations of data visualization (e.g., avoiding misleading visuals) could further enhance its value. Excellent work so far—looking forward to seeing the final poster and presentation!

**Reviewee's Comments:**
We will be sure to include a small section on the ethical considerations.

**Comment by tallapaneniv** [comment]
- Describe the goal of the project.
**Reviewer's Comment:**
The goal of this project is to create a poster that serves as a comprehensive cheat sheet for visualizations in R. It aims to educate research students without a data visualization background on selecting the best visualization techniques for their data. The project intends to cover various visualization types, demonstrate their applications, and highlight the differences between similar charts like histograms and bar graphs.

**Reviewee's Comment:**
Accurate.

- Describe the data used or collected.
**Reviewer's Comment:**
The project plans to use pre-built datasets available in R, such as:

1. MPG Dataset: Vehicle mileage data.
2. Penguin Dataset: Data on penguin species, sizes, and habitats.
3. Iris Dataset: Classic dataset on iris flowers, with features like sepal length and species type.

These datasets provide diverse data structures and characteristics, making them ideal for demonstrating different visualization types.

**Reviewee's Comment:**
Yes, the diverse nature of these in-build datasets are the reason they for chosen for this project.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
Reviewer's Comment:
The project addresses two key questions:
What role does color play in data visualization, and how can it be used effectively?
Approach:
Explore best practices for color usage in visualizations.
Demonstrate recommended color palettes for different data types using visual examples.
Compare palettes for categorical, ordinal, and continuous data

**Reviewee's Comment:**
Accurate.

- Is there anything that is unclear from the proposal?
**Reviewer's Comment:**
The proposal is clear and well-structured, but a few areas could use more detail:

Timeline Details: While the tasks are listed, the descriptions for certain steps (e.g., "Data cleaning and exploration") are vague. Specific steps or methods could be added for clarity.

Data Visualization Examples: It would be helpful to include specific visualization types planned for each dataset or research question.

**Reviewee's Comment:**
We will work on the attack tasks plan to be more detailed.

The Reason for not including Data Visualization example is because we haven't yet narrowed down on what visualizations to use but we will revise the proposal in future once we have those narrowed down.


- Provide constructive feedback on how the team might be able to improve their project.
**Reviewer's Comment:**
Expanded Dataset Scope:
While using in-built datasets simplifies the process, including one external dataset relevant to research students' interests could increase the project's impact.

Clear Comparison Framework:
For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

Interactive Elements:
Consider creating interactive visualizations (using tools like plotly) to add engagement. This would allow the audience to explore data and understand visual differences better.

File and Code Organization:
Ensure that the code used for creating visualizations is modular and well-documented. Include a README file to describe dependencies, execution instructions, and file structure.

Color Accessibility:
When discussing color usage, include accessibility considerations, such as colorblind-friendly palettes or the use of patterns for differentiation.

**Reviewee's Comment:**
The Reason we opted out of using interactive visualizations is because the end project of this project is a poster which is a static  so we thought we could create the interactivity via texts instead.

We will see to it that there is a part of poster highlighting the accessibility considerations.

The Repo structure has been updated.


- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
**Reviewer's Comment:**
For comparisons like "histogram vs. bar graph," clearly outline the evaluation framework. For example, discuss differences in usage, data types, and interpretability.

The most interesting aspect of the project is the comparison between similar visualization types (e.g., histogram vs. bar graph). Highlighting their specific use cases will provide valuable insights for the audience. Additionally, the exploration of how color influences visual effectiveness is compelling and has practical applications for researchers.

**Reviewee's Comment:**
Yes, We feel the same way.


- Provide constructive feedback on any issues with file and/or code organization.
**Reviewer's Comment:**
Use a structured folder system:

data/: For datasets.

scripts/: For R scripts.

output/: For generated visualizations.

poster/: For the final poster file.

**Reviewee's Comment:**
The Repo Structure has been updated accordingly

- (Optional) Any further comments or feedback?
**Reviewer's Comments:**
This project has significant potential to be both educational and visually engaging. Including a small section on the ethical considerations of data visualization (e.g., avoiding misleading visuals) could further enhance its value. Excellent work so far—looking forward to seeing the final poster and presentation!

**Reviewee's Comments:**
We will be sure to include a small section on the ethical considerations.
