### ISSUE TITLE
IShowcase Mock Review

### ISSUE THREAD

**Issue by Sahana2699** [INFO-526-FA24/project-2-infocrew#6]
Your work is in great but I want to see your work through solving a real life problem with the solution using the different visualizations.

**Comment by tallapaneniv** [comment]
I understand where you're getting at but visualizations are in such a way that solving a problem with them can entirely depend on the data that needs to be visualized and without knowing anything about their data more on the type of visualization useful to solving their problem can be difficult so to work around that instead we have provided some versatile visualizations and their use cases so that the audience can make the decision of which visualization to use.

Thank you for your feedback.
